# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=200)),
                ('module_route', models.CharField(max_length=200)),
                ('module_description', models.CharField(max_length=200)),
            ],
        ),
    ]
