# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_color',
            field=models.CharField(default='#64B5F6', max_length=200),
            preserve_default=False,
        ),
    ]
